[[steps]]
name = "Setup Java"
command = ["fluentci run --wasm java setup zulu-17.46.19"]

[[steps]]
name = "Setup maven"
command = ["fluentci run --wasm maven setup"]

[[steps]]
name = "Build"
command = ["mvn -q package jmeter:configure -Dmaven.test.skip-true"]
env = ["JAVA_HOME=$HOME/.local/share/mise/installs/java/zulu-17.46.19"]

[[steps]]
name = "Run tests"
command = ["java -version", "mvn -q test-compile -Dmaven.test.skip=true"]
env = ["JAVA_HOME=$HOME/.local/share/mise/installs/java/zulu-17.46.19"]

